// flow-typed signature: 50555f2a57dfdad8d64c1f92b0d9922d
// flow-typed version: <<STUB>>/css-time_v^0.1.12/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-time'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-time' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-time/src/css-time' {
  declare module.exports: any;
}

declare module 'css-time/src/css-time.min' {
  declare module.exports: any;
}

declare module 'css-time/test/css-time' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-time/src/css-time.js' {
  declare module.exports: $Exports<'css-time/src/css-time'>;
}
declare module 'css-time/src/css-time.min.js' {
  declare module.exports: $Exports<'css-time/src/css-time.min'>;
}
declare module 'css-time/test/css-time.js' {
  declare module.exports: $Exports<'css-time/test/css-time'>;
}
