// flow-typed signature: e1ac2c4e693aa05a39efa833edbb27eb
// flow-typed version: <<STUB>>/jest-matcher-deep-close-to_v^1.0.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-matcher-deep-close-to'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-matcher-deep-close-to' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-matcher-deep-close-to/lib/index' {
  declare module.exports: any;
}

declare module 'jest-matcher-deep-close-to/src/__tests__/test' {
  declare module.exports: any;
}

declare module 'jest-matcher-deep-close-to/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-matcher-deep-close-to/lib/index.js' {
  declare module.exports: $Exports<'jest-matcher-deep-close-to/lib/index'>;
}
declare module 'jest-matcher-deep-close-to/src/__tests__/test.js' {
  declare module.exports: $Exports<'jest-matcher-deep-close-to/src/__tests__/test'>;
}
declare module 'jest-matcher-deep-close-to/src/index.js' {
  declare module.exports: $Exports<'jest-matcher-deep-close-to/src/index'>;
}
