// flow-typed signature: d3ee75f9e35fa4709cca92b76402cc8e
// flow-typed version: <<STUB>>/mathquill_v^0.10.1-a/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mathquill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mathquill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mathquill/build/mathquill' {
  declare module.exports: any;
}

declare module 'mathquill/build/mathquill.min' {
  declare module.exports: any;
}

declare module 'mathquill/formula/formula' {
  declare module.exports: any;
}

declare module 'mathquill/formula/jquery.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mathquill/build/mathquill.js' {
  declare module.exports: $Exports<'mathquill/build/mathquill'>;
}
declare module 'mathquill/build/mathquill.min.js' {
  declare module.exports: $Exports<'mathquill/build/mathquill.min'>;
}
declare module 'mathquill/formula/formula.js' {
  declare module.exports: $Exports<'mathquill/formula/formula'>;
}
declare module 'mathquill/formula/jquery.min.js' {
  declare module.exports: $Exports<'mathquill/formula/jquery.min'>;
}
