// flow-typed signature: 3e77b8b54940542b525d0b91bc2027df
// flow-typed version: <<STUB>>/babel-core_v^7.0.0-beta.41/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-core/index' {
  declare module.exports: $Exports<'babel-core'>;
}
declare module 'babel-core/index.js' {
  declare module.exports: $Exports<'babel-core'>;
}
