// flow-typed signature: 6eb907beb5b688ae85f36e98791c25b5
// flow-typed version: <<STUB>>/tarjan-graph_v^1.0.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tarjan-graph'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tarjan-graph' {
  declare class Vertex {
    constructor(name: string, successors: Array<string>): Vertex,
    name: string,
    successors: Array<string>,
    index: number,
    lowLink: number,
    onStack: bool,
    visited: bool,
    reset(): void
  }

  declare class Graph {
    constructor(): Graph,
    vertices: Array<Vertex>,
    add(key: string, descendants: Array<string> | string): Graph,
    reset(): void,
    addAndVerify(key: string, descendants: Array<string> | string): Graph,
    dfs(visitor: (Vertex) => void): void,
    getDescendants(string): Array<string>,
    hasCycles(): bool,
    getStronglyConnectedComponents(): Array<Array<Vertex>>,
    getCycles(): Array<Array<Vertex>>,
    clone(): Graph,
    toDot(): string
  }

  declare export default typeof Graph;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'tarjan-graph/index' {
  declare module.exports: $Exports<'tarjan-graph'>;
}
declare module 'tarjan-graph/index.js' {
  declare module.exports: $Exports<'tarjan-graph'>;
}
