CREATE DATABASE math3d;
CREATE USER math3d_user;
GRANT ALL PRIVILEGES ON DATABASE math3d TO math3d_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO math3d_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO math3d_user;