// flow-typed signature: 50ddc9f8837792b00402639501d3f73e
// flow-typed version: <<STUB>>/jest-get-type_v^22.4.3/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-get-type'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-get-type' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-get-type/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-get-type/build/index.js' {
  declare module.exports: $Exports<'jest-get-type/build/index'>;
}
